import Footer from './Footer/Component/Footer'
import Button from './Button/'
import OtherSesion from '../components/OtherSesion'
import NavBar from './MainNavBar/NavBar/Component/NavBar'
import InputForm from './InputForm/Component/index'
import InputPassword from './InputPassword'
import InputSelectForm from './InputSelectForm/Component'
import LandingPage from '../components/Carrousel/Component/LandingPage'
import SubtitleInfoStore from './SubtitleInfoStore/Component'
import InputCard from '../components/InputCard/Component/index'
import InputCCV from '../components/InputCCV/Component/index'
import Loader from './Loader/Component/Loader'
import ButtonForm from './ButtonForm/index'
export { LandingPage, Footer, OtherSesion, InputPassword, Button, NavBar, InputForm, InputSelectForm, SubtitleInfoStore, InputCCV, InputCard, Loader, ButtonForm }
